version: "3.8"
services: 
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db
    container_name: mongodb
  # env_file: ./env/mongo.env
    # networks:
    #   - goals-net

  backend: 
    build: ./backend
    # build: 
    #   context: ./backend
    #   dockerfile: Dockerfile
    #   args:
    #     some-args: 1
    ports:
      - "80:80"
    volumes:
    # - data:/data/db
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    # env_file:
    #   - ./env/backend.env
    depends_on:
      - mongodb # only starts after mongo db starts
    container_name: goals-backend


  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend
    container_name: goals-frontend


volumes:
  data:
  logs: