version: "3.8"

services:
  server:
    image: 'nginx:stable-aline'
    ports:
      - '8000:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  #https://hub.docker.com/_/nginx

  php:
    build: 
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated # improve performance since this container shouldn't write frequently to this folder.

  mysql:

  
  # composer:
  # artisan:
  # npm:
